spring:
  application:
    name: companies-crud
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  context-path: /companies-crud
  port: 0

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}}
client:
    service-url:
      defaultZone: http://localhost:8761/eureka/