spring:
  application:
    name: companies-crud
  datasource:
    url: jdbc:postgresql://172.18.65.76:5432/companies
    username: debuggeandoideas
    password: udemy
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
 # jpa:
 #   hibernate:
 #     ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE